server {
    listen 80;
    server_name localhost;

    # Racine des fichiers statiques
    root /usr/share/nginx/html;
    index index.html;

    # Configuration pour une Single Page Application (SPA)
    # Toutes les routes non trouvées sont redirigées vers index.html pour que React Router prenne le relais.
    location / {
        try_files $uri $uri/ /index.html;
    }
}